config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/dislib:
      branch: master
      repo: https://github.com/EOSC-synergy/dislib
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-seashell-swan.sh
        container: qc.acc_blurry-rust-cuttlefish
  QC.Doc:
    repos:
      github.com/EOSC-synergy/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-harlequin-woodpecker.sh
        container: qc.doc_flabby-turquoise-caiman
      github.com/EOSC-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-orange-mole.sh
        container: qc.doc_scummy-emerald-horse
      github.com/EOSC-synergy/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-auburn-mist.sh
        container: qc.doc_fuzzy-salmon-dogfish
      github.com/EOSC-synergy/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cinnamon-mole.sh
        container: qc.doc_sloppy-seashell-cuscus
  QC.Lic:
    repos:
      github.com/EOSC-synergy/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-orange-zebra.sh
        container: qc.lic_muggy-mauve-mule
  QC.Sec:
    repos:
      github.com/EOSC-synergy/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-taupe-falcon.sh
        container: qc.sec_paltry-viridian-sheepdog
  QC.Sty:
    repos:
      github.com/EOSC-synergy/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-jade-worm.sh
        container: qc.sty_lanky-green-rabbit
      github.com/EOSC-synergy/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-viridian-dogfish.sh
        container: qc.sty_trippy-cerulean-crocodile
  QC.Ver:
    repos:
      github.com/EOSC-synergy/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-gamboge-squirrel.sh
        container: qc.ver_boozy-flax-iguana
timeout: 5400
