config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/dislib:
      branch: get_bronze
      repo: https://github.com/EOSC-synergy/dislib
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-chocolate-angora.sh
        container: qc.acc_hazy-xanthic-ferret
  QC.Doc:
    repos:
      github.com/EOSC-synergy/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-orchid-bordeaux.sh
        container: qc.doc_lovely-copper-wallaby
      github.com/EOSC-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-yellow-balinese.sh
        container: qc.doc_leaky-cinnabar-fousek
      github.com/EOSC-synergy/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-carmine-wombat.sh
        container: qc.doc_ready-persimmon-blue
      github.com/EOSC-synergy/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-silver-mayfly.sh
        container: qc.doc_greasy-pumpkin-corgi
  QC.Lic:
    repos:
      github.com/EOSC-synergy/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-platinum-dollar.sh
        container: qc.lic_crabby-pumpkin-caiman
  QC.Sec:
    repos:
      github.com/EOSC-synergy/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-salmon-devil.sh
        container: qc.sec_woozy-malachite-retriever
  QC.Sty:
    repos:
      github.com/EOSC-synergy/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-dandelion-llama.sh
        container: qc.sty_gimpy-cerise-affenpinscher
      github.com/EOSC-synergy/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-taupe-beetle.sh
        container: qc.sty_nippy-orchid-lynx
  QC.Ver:
    repos:
      github.com/EOSC-synergy/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-tangerine-moose.sh
        container: qc.ver_lousy-saffron-caracal
timeout: 5400
