config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/dislib:
      branch: get_bronze
      repo: https://github.com/EOSC-synergy/dislib
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-vermilion-bear.sh
        container: qc.acc_pretty-cinnabar-guppy
  QC.Doc:
    repos:
      github.com/EOSC-synergy/dislib find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-salmon-kangaroo.sh
        container: qc.doc_squirrely-wheat-mammoth
      github.com/EOSC-synergy/dislib git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-alizarin-cheetah.sh
        container: qc.doc_flabby-ultramarine-kingfisher
      github.com/EOSC-synergy/dislib markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-tan-armadillo.sh
        container: qc.doc_stuffy-vermilion-ibis
      github.com/EOSC-synergy/dislib restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cyan-sheepdog.sh
        container: qc.doc_wiggy-corn-jellyfish
  QC.Lic:
    repos:
      github.com/EOSC-synergy/dislib licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-platinum-squirt.sh
        container: qc.lic_bumpy-thistle-dodo
  QC.Sec:
    repos:
      github.com/EOSC-synergy/dislib bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-lavender-squirrel.sh
        container: qc.sec_stinky-chartreuse-kudu
  QC.Sty:
    repos:
      github.com/EOSC-synergy/dislib flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-vermilion-cockroach.sh
        container: qc.sty_sleepy-platinum-caiman
      github.com/EOSC-synergy/dislib hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-sapphire-llama.sh
        container: qc.sty_greasy-grey-beetle
  QC.Ver:
    repos:
      github.com/EOSC-synergy/dislib get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-tomato-lionfish.sh
        container: qc.ver_droopy-lilac-rattlesnake
timeout: 5400
